package models

import "larsa-tourism-microservices/pkg/transl"

// GetDefaultFacilityOptions returns the default set of facility options for a new exhibitor profile
func GetDefaultFacilityOptions() FacilitiesSection {
	return FacilitiesSection{
		Restaurants: []FacilityOption{
			{
				Id:         "rest_1",
				Label:      transl.Localizable[string]{"en": "Fine Dining Restaurant", "ar": "مطعم فاخر", "es": "Restaurante de alta cocina", "fr": "Restaurant gastronomique"},
				Type:       "checkbox",
				Category:   "restaurants",
				IsSelected: false,
			},
			{
				Id:         "rest_2",
				Label:      transl.Localizable[string]{"en": "Casual Dining", "ar": "مطعم عادي", "es": "Restaurante informal", "fr": "Restaurant décontracté"},
				Type:       "checkbox",
				Category:   "restaurants",
				IsSelected: false,
			},
			{
				Id:         "rest_3",
				Label:      transl.Localizable[string]{"en": "Buffet Restaurant", "ar": "مطعم بوفيه", "es": "Restaurante buffet", "fr": "Restaurant buffet"},
				Type:       "checkbox",
				Category:   "restaurants",
				IsSelected: false,
			},
			{
				Id:         "rest_4",
				Label:      transl.Localizable[string]{"en": "Specialty Restaurant", "ar": "مطعم متخصص", "es": "Restaurante especializado", "fr": "Restaurant spécialisé"},
				Type:       "checkbox",
				Category:   "restaurants",
				IsSelected: false,
			},
			{
				Id:         "rest_5",
				Label:      transl.Localizable[string]{"en": "Breakfast Included", "ar": "شامل الإفطار", "es": "Desayuno incluido", "fr": "Petit-déjeuner inclus"},
				Type:       "checkbox",
				Category:   "restaurants",
				IsSelected: false,
			},
		},
		PoolsBeaches: []FacilityOption{
			{
				Id:         "pool_1",
				Label:      transl.Localizable[string]{"en": "Outdoor Pool", "ar": "مسبح خارجي", "es": "Piscina exterior", "fr": "Piscine extérieure"},
				Type:       "checkbox",
				Category:   "poolsBeaches",
				IsSelected: false,
			},
			{
				Id:         "pool_2",
				Label:      transl.Localizable[string]{"en": "Indoor Pool", "ar": "مسبح داخلي", "es": "Piscina cubierta", "fr": "Piscine intérieure"},
				Type:       "checkbox",
				Category:   "poolsBeaches",
				IsSelected: false,
			},
			{
				Id:         "pool_3",
				Label:      transl.Localizable[string]{"en": "Private Beach Access", "ar": "دخول خاص للشاطئ", "es": "Acceso privado a la playa", "fr": "Accès privé à la plage"},
				Type:       "checkbox",
				Category:   "poolsBeaches",
				IsSelected: false,
			},
			{
				Id:         "pool_4",
				Label:      transl.Localizable[string]{"en": "Kids Pool", "ar": "مسبح للأطفال", "es": "Piscina para niños", "fr": "Piscine pour enfants"},
				Type:       "checkbox",
				Category:   "poolsBeaches",
				IsSelected: false,
			},
			{
				Id:         "pool_5",
				Label:      transl.Localizable[string]{"en": "Adults-Only Pool", "ar": "مسبح للبالغين فقط", "es": "Piscina solo para adultos", "fr": "Piscine réservée aux adultes"},
				Type:       "checkbox",
				Category:   "poolsBeaches",
				IsSelected: false,
			},
		},
		SpaGym: []FacilityOption{
			{
				Id:         "spa_1",
				Label:      transl.Localizable[string]{"en": "Full-Service Spa", "ar": "سبا متكامل الخدمات", "es": "Spa de servicio completo", "fr": "Spa complet"},
				Type:       "checkbox",
				Category:   "spaGym",
				IsSelected: false,
			},
			{
				Id:         "spa_2",
				Label:      transl.Localizable[string]{"en": "Fitness Center", "ar": "مركز لياقة بدنية", "es": "Gimnasio", "fr": "Centre de remise en forme"},
				Type:       "checkbox",
				Category:   "spaGym",
				IsSelected: false,
			},
			{
				Id:         "spa_3",
				Label:      transl.Localizable[string]{"en": "Yoga Classes", "ar": "دروس يوغا", "es": "Clases de yoga", "fr": "Cours de yoga"},
				Type:       "checkbox",
				Category:   "spaGym",
				IsSelected: false,
			},
			{
				Id:         "spa_4",
				Label:      transl.Localizable[string]{"en": "Massage Services", "ar": "خدمات التدليك", "es": "Servicios de masaje", "fr": "Services de massage"},
				Type:       "checkbox",
				Category:   "spaGym",
				IsSelected: false,
			},
			{
				Id:         "spa_5",
				Label:      transl.Localizable[string]{"en": "Sauna/Steam Room", "ar": "ساونا / غرفة بخار", "es": "Sauna / Baño de vapor", "fr": "Sauna / Hammam"},
				Type:       "checkbox",
				Category:   "spaGym",
				IsSelected: false,
			},
		},
		HotelServices: []FacilityOption{
			{
				Id:         "serv_1",
				Label:      transl.Localizable[string]{"en": "24-Hour Front Desk", "ar": "مكتب استقبال 24 ساعة", "es": "Recepción 24 horas", "fr": "Réception 24h/24"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_2",
				Label:      transl.Localizable[string]{"en": "Concierge Service", "ar": "خدمة الكونسيرج", "es": "Servicio de conserjería", "fr": "Service de conciergerie"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_3",
				Label:      transl.Localizable[string]{"en": "Room Service", "ar": "خدمة الغرف", "es": "Servicio de habitaciones", "fr": "Service d'étage"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_4",
				Label:      transl.Localizable[string]{"en": "Airport Shuttle", "ar": "خدمة نقل المطار", "es": "Transporte al aeropuerto", "fr": "Navette aéroport"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_5",
				Label:      transl.Localizable[string]{"en": "Laundry Service", "ar": "خدمة غسيل الملابس", "es": "Servicio de lavandería", "fr": "Service de blanchisserie"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_6",
				Label:      transl.Localizable[string]{"en": "Free Parking", "ar": "موقف سيارات مجاني", "es": "Estacionamiento gratis", "fr": "Parking gratuit"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
			{
				Id:         "serv_7",
				Label:      transl.Localizable[string]{"en": "Free WiFi", "ar": "واي فاي مجاني", "es": "WiFi gratis", "fr": "WiFi gratuit"},
				Type:       "checkbox",
				Category:   "hotelServices",
				IsSelected: false,
			},
		},
		Business: []FacilityOption{
			{
				Id:         "biz_1",
				Label:      transl.Localizable[string]{"en": "Business Center", "ar": "مركز أعمال", "es": "Centro de negocios", "fr": "Centre d'affaires"},
				Type:       "checkbox",
				Category:   "business",
				IsSelected: false,
			},
			{
				Id:         "biz_2",
				Label:      transl.Localizable[string]{"en": "Meeting Rooms", "ar": "غرف اجتماعات", "es": "Salas de reuniones", "fr": "Salles de réunion"},
				Type:       "checkbox",
				Category:   "business",
				IsSelected: false,
			},
			{
				Id:         "biz_3",
				Label:      transl.Localizable[string]{"en": "Conference Facilities", "ar": "مرافق المؤتمرات", "es": "Instalaciones para conferencias", "fr": "Installations de conférence"},
				Type:       "checkbox",
				Category:   "business",
				IsSelected: false,
			},
			{
				Id:         "biz_4",
				Label:      transl.Localizable[string]{"en": "Event Space", "ar": "مساحة للفعاليات", "es": "Espacio para eventos", "fr": "Espace événementiel"},
				Type:       "checkbox",
				Category:   "business",
				IsSelected: false,
			},
		},
		KidsFacilities: []FacilityOption{
			{
				Id:         "kids_1",
				Label:      transl.Localizable[string]{"en": "Kids Club", "ar": "نادي الأطفال", "es": "Club infantil", "fr": "Club enfants"},
				Type:       "checkbox",
				Category:   "kidsFacilities",
				IsSelected: false,
			},
			{
				Id:         "kids_2",
				Label:      transl.Localizable[string]{"en": "Babysitting/Childcare", "ar": "رعاية الأطفال", "es": "Cuidado de niños", "fr": "Garde d'enfants"},
				Type:       "checkbox",
				Category:   "kidsFacilities",
				IsSelected: false,
			},
			{
				Id:         "kids_3",
				Label:      transl.Localizable[string]{"en": "Children's Playground", "ar": "ملعب للأطفال", "es": "Parque infantil", "fr": "Aire de jeux pour enfants"},
				Type:       "checkbox",
				Category:   "kidsFacilities",
				IsSelected: false,
			},
			{
				Id:         "kids_4",
				Label:      transl.Localizable[string]{"en": "Family Rooms", "ar": "غرف عائلية", "es": "Habitaciones familiares", "fr": "Chambres familiales"},
				Type:       "checkbox",
				Category:   "kidsFacilities",
				IsSelected: false,
			},
		},
		Recreational: []FacilityOption{
			{
				Id:         "rec_1",
				Label:      transl.Localizable[string]{"en": "Tennis Courts", "ar": "ملاعب تنس", "es": "Pistas de tenis", "fr": "Courts de tennis"},
				Type:       "checkbox",
				Category:   "recreational",
				IsSelected: false,
			},
			{
				Id:         "rec_2",
				Label:      transl.Localizable[string]{"en": "Golf Course", "ar": "ملعب جولف", "es": "Campo de golf", "fr": "Parcours de golf"},
				Type:       "checkbox",
				Category:   "recreational",
				IsSelected: false,
			},
			{
				Id:         "rec_3",
				Label:      transl.Localizable[string]{"en": "Water Sports", "ar": "رياضات مائية", "es": "Deportes acuáticos", "fr": "Sports nautiques"},
				Type:       "checkbox",
				Category:   "recreational",
				IsSelected: false,
			},
			{
				Id:         "rec_4",
				Label:      transl.Localizable[string]{"en": "Bicycle Rental", "ar": "تأجير الدراجات", "es": "Alquiler de bicicletas", "fr": "Location de vélos"},
				Type:       "checkbox",
				Category:   "recreational",
				IsSelected: false,
			},
			{
				Id:         "rec_5",
				Label:      transl.Localizable[string]{"en": "Entertainment Programs", "ar": "برامج ترفيهية", "es": "Programas de entretenimiento", "fr": "Programmes d'animation"},
				Type:       "checkbox",
				Category:   "recreational",
				IsSelected: false,
			},
		},
	}
}
